//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boeking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boeking()
        {
            this.Beest = new HashSet<Beest>();
            this.Accessoires = new HashSet<Accessoires>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int CustomerId { get; set; }
        public decimal totalPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beest> Beest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accessoires> Accessoires { get; set; }
    }
}
