//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOEF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Boeking = new HashSet<Boeking>();
        }
    
        public int Id { get; set; }
        [Required]
        public string Firstname { get; set; }
        public string Infix { get; set; }
        [Required]
        public string Lastname { get; set; }
        [Required]
        public string Adress { get; set; }
        [Required]
        public string Mail { get; set; }
        [Range(99999999,int.MaxValue, ErrorMessage = "Telefoonnummer is te kort")]
        public Nullable<int> Telephone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boeking> Boeking { get; set; }
    }
}
