//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOEF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BOEFEntities : DbContext
    {
        public BOEFEntities()
            : base("name=BOEFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Accessoires> Accessoires { get; set; }
        public virtual DbSet<Beest> Beest { get; set; }
        public virtual DbSet<BeestType> BeestType { get; set; }
        public virtual DbSet<Boeking> Boeking { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<BeestImage> BeestImage { get; set; }
        public virtual DbSet<AccessoireImage> AccessoireImage { get; set; }
    }
}
